theme: jekyll-theme-architect
title: Epica, compiti sull' Iliadeo
description: Compiti per le vacanze, tra cui parafrasi, esercizi e recensioni di libri.
markdown: redcarpet
redcarpet:
  extensions:
    lax_spacing
