theme: jekyll-theme-minimal
title: Epica, compiti sull' Iliade
description: Compiti per le vacanze, tra cui parafrasi, esercizi e recensioni di libri.
markdown: CommonMarkGhPages
commonmark:
  options:["SMART", "FOOTNOTES"]
  extensions: ["strikethrough","autolink","table","tagfilter"]
